# ~/.config/hypr/hyprland.conf

source = ~/.config/hypr/conf/env.conf
source = ~/.config/hypr/conf/input.conf
source = ~/.config/hypr/conf/look.conf
source = ~/.config/hypr/conf/binds.conf
source = ~/.config/hypr/conf/rules.conf

# Start the desktop service bundle
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE DISPLAY HYPRLAND_INSTANCE_SIGNATURE
exec-once = systemctl --user start hyprland-session.target

# Basic monitor fallback
monitor = ,preferred,auto,1

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
}