input {
    kb_layout = us
    follow_mouse = 1
    touchpad {
        natural_scroll = false
    }
    sensitivity = 0
}

general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    resize_on_border = true
    allow_tearing = false
    layout = dwindle
}

dwindle {
    pseudotile = true
    preserve_split = true
}