decoration {
    rounding = 8

    blur {
        enabled = false
    }

    shadow {
        enabled = false
    }
}

animations {
    enabled = yes

    bezier = easeOut, 0.25, 0.9, 0.3, 1.0

    animation = windows, 1, 4, easeOut
    animation = windowsOut, 1, 4, easeOut
    animation = border, 1, 5, easeOut
    animation = fade, 1, 4, easeOut
    animation = workspaces, 1, 4, easeOut
}

general {
    col.active_border = rgba(88c0d0ff)
    col.inactive_border = rgba(4c566a88)
}