windowrule {
    match:class = ^(pavucontrol)$
    float = true
}

windowrule {
    match:class = ^(blueman-manager)$
    float = true
}

windowrule {
    match:class = ^(nm-connection-editor)$
    float = true
}